# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psite', '0002_collaborator_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
