# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psite', '0003_track_track_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='soundcloud_url',
            new_name='soundcloud_html',
        ),
    ]
