# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('psite', '0004_auto_20160922_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 9, 22, 15, 11, 17, 571602, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
