# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psite', '0006_auto_20161003_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='apple_music_html',
            field=models.CharField(default='<a href="https://geo.itunes.apple.com/us/album/out-on-the-edge/id1142088168?i=1142088406&mt=1&app=music" style="display:inline-block;overflow:hidden;background:url(//tools.applemusic.com/assets/shared/badges/en-us/music-lrg.svg) no-repeat;width:115px;height:40px;"></a>', max_length=700, verbose_name='Apple Music HTML'),
            preserve_default=False,
        ),
    ]
