# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psite', '0008_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
