# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psite', '0010_editabletext'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Register',
        ),
    ]
