# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psite', '0011_auto_20161017_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editabletext',
            options={'verbose_name': 'Editable Text', 'verbose_name_plural': 'Editable Text Sections'},
        ),
    ]
