# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psite', '0012_auto_20161018_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfrom', models.EmailField(max_length=254)),
                ('msubject', models.CharField(max_length=60)),
                ('mcontent', models.TextField()),
            ],
        ),
    ]
